Add hostData support for widgets
microsoft/devhome pull request #1585
Opened 2023-09-22 03:35 UTC by guimafelipe

## Summary of the pull request

This change adds the hostData parameter to be passed to widgets when rendering. With this, widgets will be able to know which size they are being rendered and change their view accordingly. This will be needed to have the complete experience for future extensions.
<img width="236" alt="image" src="https://github.com/microsoft/devhome/assets/13912953/e3ac4b61-0de0-4692-a131-a3c6c6bf84ba">

<img width="237" alt="image" src="https://github.com/microsoft/devhome/assets/13912953/be9641b1-9be4-44b6-81cc-8f5a94faaad3">

## References and relevant issues

## Detailed description of the pull request / Additional comments

## Validation steps performed

## PR checklist
- [ ] Closes #xxx
- [ ] Tests added/passed
- [ ] Documentation updated

2023-09-22 16:11 UTC, krschau requested changes
So excited we're including this functionality!

2023-09-22 16:11 UTC, krschau commented on tools/Dashboard/DevHome.Dashboard/ViewModels/WidgetViewModel.cs
> +        var hostData = new JsonObject
Can you move this down to where we use the host data? That way if we error out in between, we don't create this object that will ultimately not be used.

2023-09-22 21:44 UTC, krschau approved these changes

2023-10-12 17:08 UTC, AmelBawa-msft approved these changes

2023-10-12 20:12 UTC, merged