SettingsCard design improvements
microsoft/devhome pull request #688
Opened 2023-05-23 10:08 UTC by niels9001

## Summary of the pull request
This PR adds some styling consistency to various pages where `SettingsCards` are used. These changes are inline with design specifications (Windows Visual Library in Figma) and other 1P apps (like PowerToys)

Machinge config (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/d7ca6051-606d-4722-8bf8-8c8799e89ede)

Feedback (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/6600fe24-ea2c-4d98-8059-6e00ee1c4bc8)

Settings (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/2d003508-0892-430d-8166-2cce1678ee33)

Preferences (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/7a4f25a7-345f-4254-8ba5-1d50f3d1dd65)

Accounts (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/dfb60c88-172a-4188-bad1-20e0c37844e2)

Extensions (before vs. after)
![image](https://github.com/microsoft/devhome/assets/9866362/5e03ce4c-1565-4546-ae8a-76a74856b4bc)

## References and relevant issues

## Detailed description of the pull request / Additional comments

## Validation steps performed

## PR checklist
- [X] Closes #664 #671 #560
- [ ] Tests added/passed
- [ ] Documentation updated

2023-05-23 17:50 UTC, EricJohnson327 approved these changes

2023-05-23 18:10 UTC, asklar approved these changes

2023-05-23 18:39 UTC, krschau commented on settings/DevHome.Settings/Strings/en-us/Resources.resw
> +	<data name="Settings_Theme.Description" xml:space="preserve">
Nit: too much whitespace

2023-05-23 18:40 UTC, krschau commented on settings/DevHome.Settings/Strings/en-us/Resources.resw
> +    <value>Windows default</value>
Whitespace

2023-05-23 18:49 UTC, krschau requested changes

2023-05-23 18:49 UTC, krschau commented on settings/DevHome.Settings/Strings/en-us/Resources.resw
> +	  <comment>Windows refers to the Operating system</comment>
```suggestion
    <value>Windows default</value>
    <comment>Windows refers to the Operating system</comment>
```

Spaces, not tabs

2023-05-23 18:49 UTC, krschau commented on settings/DevHome.Settings/Strings/en-us/Resources.resw
> +	<data name="Settings_Theme.Description" xml:space="preserve">
```suggestion
  <data name="Settings_Theme.Description" xml:space="preserve">

```

2023-05-23 19:18 UTC, krschau approved these changes

2023-05-23 22:28 UTC, niels9001 commented
/azp run

2023-05-23 23:20 UTC, merged

2023-06-15 22:10 UTC, EricJohnson327 commented
Fixes #1144